#对swintransformer网络模型的设置

MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.25
  NUM_CLASSES: 1
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 4, 4, 12, 4 ]
    NUM_HEADS: [ 3, 6, 12, 24]
    WINDOW_SIZE: 7